In [1]:
# Concrete

## Import Necessary Libraries

In [2]:
import pandas as pd
import numpy as np

import keras
from keras.models import Sequential
from keras.layers import Dense

## Import Data

In [33]:
df = pd.read_csv("https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv")
df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

## Data info

In [4]:
df.shape

(1030, 9)

In [5]:
df.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [6]:
df.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

## Split Predictors and Target values

In [7]:
concrete_data_columns = df.columns

X = df.drop('Strength', 1).values # all columns except Strength
y = df['Strength'] # Strength column

C:\Users\Maxter\AppData\Local\Temp/ipykernel_19612/464899849.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X = df.drop('Strength', 1).values # all columns except Strength

## Normalize Data (new!!)

In [8]:
X_norm = (X - X.mean()) / X.std()

## Split data into Train and Test sets

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_norm, y, test_size = 0.3, random_state=6)

In [10]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(721, 8)
(309, 8)
(721,)
(309,)

## Build and Train Neural Network

In [11]:
n_cols = X.shape[1]
n_cols

8

In [12]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    # model.add(Dense(10, activation='relu'))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [28]:
# build the model
model = regression_model()

# train
np.random.seed(45)
model.fit(X_train, y_train, epochs=50, verbose=1)

Epoch 1/50
23/23 [==============================] - 0s 2ms/step - loss: 1500.1389
Epoch 2/50
23/23 [==============================] - 0s 1ms/step - loss: 1484.4003
Epoch 3/50
23/23 [==============================] - 0s 2ms/step - loss: 1468.5092
Epoch 4/50
23/23 [==============================] - 0s 2ms/step - loss: 1452.2200
Epoch 5/50
23/23 [==============================] - 0s 2ms/step - loss: 1434.8082
Epoch 6/50
23/23 [==============================] - 0s 2ms/step - loss: 1416.2830
Epoch 7/50
23/23 [==============================] - 0s 2ms/step - loss: 1396.5149
Epoch 8/50
23/23 [==============================] - 0s 2ms/step - loss: 1375.4915
Epoch 9/50
23/23 [==============================] - 0s 2ms/step - loss: 1352.8679
Epoch 10/50
23/23 [==============================] - 0s 2ms/step - loss: 1328.4514
Epoch 11/50
23/23 [==============================] - 0s 2ms/step - loss: 1302.1709
Epoch 12/50
23/23 [==============================] - 0s 2ms/step - loss: 1274.3326
Epoch 13/50
23/23 [==============================] - 0s 2ms/step - loss: 1244.4344
Epoch 14/50
23/23 [==============================] - 0s 2ms/step - loss: 1213.3030
Epoch 15/50
23/23 [==============================] - 0s 2ms/step - loss: 1180.6078
Epoch 16/50
23/23 [==============================] - 0s 2ms/step - loss: 1146.5114
Epoch 17/50
23/23 [==============================] - 0s 2ms/step - loss: 1111.4526
Epoch 18/50
23/23 [==============================] - 0s 2ms/step - loss: 1075.6289
Epoch 19/50
23/23 [==============================] - 0s 2ms/step - loss: 1038.9246
Epoch 20/50
23/23 [==============================] - 0s 2ms/step - loss: 1001.9537
Epoch 21/50
23/23 [==============================] - 0s 3ms/step - loss: 964.3288
Epoch 22/50
23/23 [==============================] - 0s 2ms/step - loss: 927.1929
Epoch 23/50
23/23 [==============================] - 0s 3ms/step - loss: 889.5359
Epoch 24/50
23/23 [==============================] - 0s 2ms/step - loss: 852.6364
Epoch 25/50
23/23 [==============================] - 0s 2ms/step - loss: 816.1133
Epoch 26/50
23/23 [==============================] - 0s 2ms/step - loss: 779.9866
Epoch 27/50
23/23 [==============================] - 0s 2ms/step - loss: 744.6527
Epoch 28/50
23/23 [==============================] - 0s 2ms/step - loss: 710.4529
Epoch 29/50
23/23 [==============================] - 0s 2ms/step - loss: 676.8500
Epoch 30/50
23/23 [==============================] - 0s 2ms/step - loss: 644.9241
Epoch 31/50
23/23 [==============================] - 0s 3ms/step - loss: 613.7425
Epoch 32/50
23/23 [==============================] - 0s 2ms/step - loss: 584.1934
Epoch 33/50
23/23 [==============================] - 0s 3ms/step - loss: 556.0938
Epoch 34/50
23/23 [==============================] - 0s 2ms/step - loss: 529.4229
Epoch 35/50
23/23 [==============================] - 0s 2ms/step - loss: 504.5068
Epoch 36/50
23/23 [==============================] - 0s 1ms/step - loss: 480.7952
Epoch 37/50
23/23 [==============================] - 0s 2ms/step - loss: 458.7660
Epoch 38/50
23/23 [==============================] - 0s 2ms/step - loss: 438.5411
Epoch 39/50
23/23 [==============================] - 0s 2ms/step - loss: 419.6576
Epoch 40/50
23/23 [==============================] - 0s 2ms/step - loss: 402.5572
Epoch 41/50
23/23 [==============================] - 0s 2ms/step - loss: 386.5774
Epoch 42/50
23/23 [==============================] - 0s 2ms/step - loss: 372.2943
Epoch 43/50
23/23 [==============================] - 0s 2ms/step - loss: 359.3258
Epoch 44/50
23/23 [==============================] - 0s 2ms/step - loss: 347.6911
Epoch 45/50
23/23 [==============================] - 0s 2ms/step - loss: 336.9483
Epoch 46/50
23/23 [==============================] - 0s 2ms/step - loss: 327.9045
Epoch 47/50
23/23 [==============================] - 0s 2ms/step - loss: 319.4826
Epoch 48/50
23/23 [==============================] - 0s 2ms/step - loss: 312.5083
Epoch 49/50
23/23 [==============================] - 0s 2ms/step - loss: 306.0942
Epoch 50/50
23/23 [==============================] - 0s 1ms/step - loss: 300.8112

## Predict and Evaluate

In [29]:
predictions = model.predict(X_test)
print(predictions.shape)
print(y_test.shape)

10/10 [==============================] - 0s 2ms/step
(309, 1)
(309,)

In [30]:
predictions = predictions[0::]
y_test = np.asarray(y_test)
y_test

array([58.8 , 31.35, 50.77, 26.23, 44.61, 37.81, 54.1 , 36.94, 40.87,
       40.86, 24.13, 49.8 , 32.04, 24.  , 79.3 ,  8.06, 44.3 , 24.5 ,
       44.61,  8.54, 26.97, 45.3 , 39.66, 27.42, 37.92, 28.63, 11.17,
       28.8 , 34.24, 64.9 , 71.3 , 50.94, 46.68, 56.14, 43.01, 41.93,
       13.46, 19.77, 45.84, 37.36, 14.64, 28.94, 23.79, 38.6 , 82.6 ,
       64.9 , 22.63, 35.96, 36.8 , 45.37, 28.99, 21.86, 29.55, 24.28,
       71.3 , 23.22, 67.57, 50.53, 76.8 , 53.1 , 18.03, 43.38, 30.14,
       25.37, 20.87, 31.64, 33.95, 17.96, 55.9 , 71.3 , 32.1 , 56.14,
       28.02, 26.2 , 25.45, 39.38, 72.99, 50.46, 34.2 , 39.3 , 42.13,
       28.99, 15.58, 15.09, 26.4 , 14.94, 14.5 , 52.96, 22.14, 32.53,
       61.23, 17.37, 61.07, 52.91, 41.3 , 40.15, 59.8 , 21.92, 24.28,
       45.71, 35.57, 65.2 , 17.57, 66.1 , 55.6 , 66.78, 55.16, 67.11,
       11.47, 26.14, 32.24, 42.13, 31.74, 44.3 , 33.4 ,  4.9 , 59.49,
       29.59, 17.82, 12.18, 52.42, 44.42, 33.49, 10.73, 19.42, 23.35,
       41.54, 55.55, 37.17, 21.16, 40.06, 47.74, 77.3 , 14.99, 43.38,
       45.94, 19.77, 39.32, 24.1 ,  6.9 , 40.27, 33.02, 52.2 , 57.21,
       39.84, 33.7 , 15.52, 46.2 , 15.75, 17.24, 22.93, 18.03, 79.99,
       17.34, 60.95, 19.99, 40.86, 26.74, 43.5 , 15.05, 23.52, 77.3 ,
       22.75, 33.27, 52.3 , 41.67, 29.59, 29.87, 25.62, 10.09, 31.9 ,
       79.3 , 29.45, 15.04,  6.27, 74.5 , 32.11, 65.7 , 71.62, 47.71,
       55.02, 12.46, 33.36, 70.7 , 43.06, 30.12, 37.68, 25.72, 60.32,
       61.46, 19.99, 49.77, 17.6 , 32.33, 31.88, 45.08, 15.57, 39.16,
       68.75, 32.76, 51.02, 33.7 , 25.02, 41.37, 62.5 , 19.01, 39.27,
       40.57, 21.97, 36.99, 52.61, 33.94, 33.42, 17.95, 67.87, 17.2 ,
       53.66, 18.28, 13.29, 19.42, 11.85, 37.72, 33.54, 19.69, 20.77,
       16.26, 77.3 , 45.9 , 25.89, 24.  , 13.29, 42.55, 35.76, 35.3 ,
       20.92, 80.2 , 40.06, 18.13, 33.  , 35.3 , 25.22, 61.24, 40.93,
       23.84, 55.45, 13.36, 14.6 , 22.32, 25.12, 43.25,  7.84, 47.81,
       61.99, 27.68, 15.42, 13.71, 33.12, 24.99, 32.63, 39.  , 71.7 ,
       49.25, 20.08, 14.7 , 42.33, 38.07, 43.57, 10.39, 32.88, 23.52,
       26.86, 41.72, 32.01,  9.01,  4.83, 66.82, 64.02, 22.72, 31.97,
       33.31, 60.28, 38.7 , 52.01, 66.9 , 35.1 , 27.34, 53.3 , 43.7 ,
       39.4 , 31.27, 81.75, 56.63, 33.69, 64.3 , 40.71, 69.84, 23.85,
       38.5 , 55.64, 41.05, 55.9 , 40.66, 74.99, 39.46, 68.3 , 46.93,
       13.52, 29.55, 36.56])

In [31]:
predictions

array([[33.4417  ],
       [30.98447 ],
       [30.333664],
       [27.320412],
       [26.454933],
       [26.358845],
       [32.56859 ],
       [32.31247 ],
       [28.466413],
       [29.036398],
       [29.006788],
       [26.913046],
       [31.726183],
       [32.594135],
       [28.754221],
       [29.565313],
       [29.901999],
       [33.00905 ],
       [26.46897 ],
       [26.298347],
       [25.839495],
       [29.98234 ],
       [26.865189],
       [30.944347],
       [28.655874],
       [26.282625],
       [33.52869 ],
       [27.602747],
       [28.108759],
       [26.983624],
       [29.48961 ],
       [27.029928],
       [31.673994],
       [30.291174],
       [25.717403],
       [25.448862],
       [28.19295 ],
       [29.18662 ],
       [29.813265],
       [27.30752 ],
       [30.338108],
       [28.029158],
       [28.723944],
       [29.906107],
       [29.05652 ],
       [28.611567],
       [30.226782],
       [30.815947],
       [29.484993],
       [28.9804  ],
       [24.785963],
       [31.95517 ],
       [28.702566],
       [30.216034],
       [29.48961 ],
       [32.141853],
       [34.381535],
       [27.390604],
       [29.590614],
       [28.005747],
       [28.7382  ],
       [26.924067],
       [32.567722],
       [32.24839 ],
       [33.13458 ],
       [32.13846 ],
       [26.616846],
       [30.177862],
       [29.734741],
       [29.48961 ],
       [29.492315],
       [25.172632],
       [30.09298 ],
       [31.29854 ],
       [32.57105 ],
       [31.11762 ],
       [29.999166],
       [28.383436],
       [30.154608],
       [29.18382 ],
       [29.091562],
       [24.79616 ],
       [33.1052  ],
       [28.032976],
       [31.1395  ],
       [28.048464],
       [32.955524],
       [28.995   ],
       [30.807169],
       [28.71044 ],
       [29.264498],
       [30.315016],
       [30.291174],
       [29.056303],
       [34.060364],
       [29.317846],
       [27.310923],
       [26.020319],
       [31.94627 ],
       [30.660505],
       [29.494007],
       [31.038336],
       [30.346746],
       [29.471067],
       [30.535522],
       [30.115126],
       [29.207872],
       [29.502075],
       [33.836308],
       [27.499266],
       [29.50169 ],
       [26.558489],
       [32.83559 ],
       [26.213858],
       [28.408846],
       [29.72598 ],
       [30.441969],
       [29.998869],
       [30.099174],
       [29.976484],
       [28.8758  ],
       [30.618013],
       [29.143427],
       [29.067251],
       [31.05277 ],
       [30.909834],
       [27.77986 ],
       [28.898294],
       [26.948938],
       [32.73853 ],
       [28.281624],
       [31.244524],
       [29.162771],
       [32.792023],
       [27.120745],
       [30.023195],
       [32.73796 ],
       [26.369663],
       [29.520853],
       [26.908669],
       [24.033949],
       [26.86007 ],
       [29.742687],
       [28.771112],
       [22.593445],
       [28.523987],
       [28.666853],
       [29.592089],
       [26.861977],
       [29.47443 ],
       [24.731874],
       [28.736372],
       [32.73455 ],
       [33.283558],
       [31.28454 ],
       [27.605623],
       [32.02469 ],
       [30.183252],
       [29.580078],
       [33.273174],
       [28.359453],
       [29.162771],
       [31.93994 ],
       [30.158293],
       [32.751675],
       [31.919123],
       [30.086153],
       [25.818762],
       [32.031345],
       [29.564001],
       [32.49271 ],
       [28.754221],
       [30.760765],
       [31.43132 ],
       [32.211895],
       [29.79191 ],
       [29.220839],
       [28.490608],
       [30.839252],
       [27.40999 ],
       [26.872252],
       [28.44972 ],
       [32.618126],
       [30.610392],
       [31.02748 ],
       [29.147078],
       [29.47159 ],
       [31.974432],
       [31.294592],
       [31.347155],
       [27.598139],
       [28.83093 ],
       [30.377668],
       [30.625105],
       [28.602608],
       [31.289114],
       [28.694857],
       [27.94534 ],
       [30.115126],
       [28.924261],
       [32.501637],
       [30.186615],
       [30.909834],
       [31.8743  ],
       [32.51894 ],
       [29.899176],
       [29.831453],
       [30.299051],
       [28.967455],
       [30.59492 ],
       [32.85866 ],
       [32.454704],
       [28.189135],
       [30.175333],
       [27.600203],
       [27.187204],
       [26.916193],
       [28.076536],
       [28.815826],
       [28.004522],
       [32.981   ],
       [26.136349],
       [28.93131 ],
       [32.732704],
       [32.02385 ],
       [32.671787],
       [29.162771],
       [31.897083],
       [27.365873],
       [32.60568 ],
       [28.81359 ],
       [31.811619],
       [31.96546 ],
       [29.781433],
       [30.644869],
       [26.340216],
       [28.2712  ],
       [33.214256],
       [28.876947],
       [29.781433],
       [32.62486 ],
       [29.25443 ],
       [30.500242],
       [28.21803 ],
       [32.207306],
       [30.168667],
       [32.707024],
       [30.040266],
       [30.73379 ],
       [28.981688],
       [33.654224],
       [28.434286],
       [30.325686],
       [26.684486],
       [29.301172],
       [32.977837],
       [24.454176],
       [32.13785 ],
       [26.942072],
       [29.062582],
       [28.327372],
       [28.774633],
       [30.07844 ],
       [32.188545],
       [25.69196 ],
       [29.36926 ],
       [25.89313 ],
       [27.83404 ],
       [28.977236],
       [28.033537],
       [26.774134],
       [28.3187  ],
       [29.700682],
       [33.343723],
       [27.88073 ],
       [30.88326 ],
       [30.732311],
       [31.246973],
       [31.867928],
       [24.765146],
       [33.09074 ],
       [31.615273],
       [30.863144],
       [31.345785],
       [29.474161],
       [31.708189],
       [26.955185],
       [24.606699],
       [27.743876],
       [29.90692 ],
       [31.707838],
       [28.902237],
       [26.510334],
       [31.446886],
       [30.247158],
       [32.17721 ],
       [30.022787],
       [31.218225],
       [31.00548 ],
       [29.182941],
       [29.734741],
       [32.374874],
       [34.392048],
       [27.527018],
       [30.290392],
       [24.641397],
       [31.742655],
       [28.033796],
       [30.971697]], dtype=float32)

In [32]:
print("Mean absolute error: %.2f" % np.mean(np.absolute(predictions - y_test)))
print("Residual sum of squares (MSE): %.2f" % np.mean((predictions - y_test) ** 2))
from sklearn.metrics import r2_score
print("R2-score: %.2f" % r2_score(y_test, predictions) )

Mean absolute error: 15.38
Residual sum of squares (MSE): 391.12
R2-score: -0.22

# With data normalization, MSE decreased from 516.03 to 391.12 !