In [1]:
# Concrete

## Import Necessary Libraries

In [2]:
import pandas as pd
import numpy as np

import keras
from keras.models import Sequential
from keras.layers import Dense

## Import Data

In [23]:
df = pd.read_csv("https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv")
df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

## Data info

In [4]:
df.shape

(1030, 9)

In [5]:
df.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [6]:
df.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

## Split Predictors and Target values

In [7]:
concrete_data_columns = df.columns

X = df.drop('Strength', 1).values # all columns except Strength
y = df['Strength'] # Strength column

C:\Users\Maxter\AppData\Local\Temp/ipykernel_27372/464899849.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X = df.drop('Strength', 1).values # all columns except Strength

## Normalize Data (new!!)

In [8]:
X_norm = (X - X.mean()) / X.std()

## Split data into Train and Test sets

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_norm, y, test_size = 0.3, random_state=6)

In [10]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(721, 8)
(309, 8)
(721,)
(309,)

## Build and Train Neural Network

In [11]:
n_cols = X.shape[1]
n_cols

8

In [12]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [18]:
# build the model
model = regression_model()

# train
np.random.seed(45)
model.fit(X_train, y_train, epochs=50, verbose=1)

Epoch 1/50
23/23 [==============================] - 0s 2ms/step - loss: 1468.9308
Epoch 2/50
23/23 [==============================] - 0s 2ms/step - loss: 1439.6274
Epoch 3/50
23/23 [==============================] - 0s 2ms/step - loss: 1384.2158
Epoch 4/50
23/23 [==============================] - 0s 2ms/step - loss: 1282.7188
Epoch 5/50
23/23 [==============================] - 0s 2ms/step - loss: 1122.2003
Epoch 6/50
23/23 [==============================] - 0s 2ms/step - loss: 901.9588
Epoch 7/50
23/23 [==============================] - 0s 2ms/step - loss: 646.2462
Epoch 8/50
23/23 [==============================] - 0s 2ms/step - loss: 414.6813
Epoch 9/50
23/23 [==============================] - 0s 2ms/step - loss: 284.6009
Epoch 10/50
23/23 [==============================] - 0s 2ms/step - loss: 253.1969
Epoch 11/50
23/23 [==============================] - 0s 2ms/step - loss: 250.2783
Epoch 12/50
23/23 [==============================] - 0s 2ms/step - loss: 248.1367
Epoch 13/50
23/23 [==============================] - 0s 2ms/step - loss: 246.5086
Epoch 14/50
23/23 [==============================] - 0s 2ms/step - loss: 245.4385
Epoch 15/50
23/23 [==============================] - 0s 2ms/step - loss: 243.6021
Epoch 16/50
23/23 [==============================] - 0s 2ms/step - loss: 242.0974
Epoch 17/50
23/23 [==============================] - 0s 2ms/step - loss: 240.7904
Epoch 18/50
23/23 [==============================] - 0s 2ms/step - loss: 239.4536
Epoch 19/50
23/23 [==============================] - 0s 2ms/step - loss: 238.2497
Epoch 20/50
23/23 [==============================] - 0s 2ms/step - loss: 236.6526
Epoch 21/50
23/23 [==============================] - 0s 2ms/step - loss: 235.5723
Epoch 22/50
23/23 [==============================] - 0s 2ms/step - loss: 234.5180
Epoch 23/50
23/23 [==============================] - 0s 2ms/step - loss: 233.0197
Epoch 24/50
23/23 [==============================] - 0s 2ms/step - loss: 232.2574
Epoch 25/50
23/23 [==============================] - 0s 2ms/step - loss: 230.5785
Epoch 26/50
23/23 [==============================] - 0s 2ms/step - loss: 229.6633
Epoch 27/50
23/23 [==============================] - 0s 2ms/step - loss: 228.3249
Epoch 28/50
23/23 [==============================] - 0s 2ms/step - loss: 227.5995
Epoch 29/50
23/23 [==============================] - 0s 2ms/step - loss: 225.7114
Epoch 30/50
23/23 [==============================] - 0s 2ms/step - loss: 224.7435
Epoch 31/50
23/23 [==============================] - 0s 2ms/step - loss: 224.0062
Epoch 32/50
23/23 [==============================] - 0s 2ms/step - loss: 222.7783
Epoch 33/50
23/23 [==============================] - 0s 2ms/step - loss: 221.2798
Epoch 34/50
23/23 [==============================] - 0s 2ms/step - loss: 220.1570
Epoch 35/50
23/23 [==============================] - 0s 2ms/step - loss: 219.2270
Epoch 36/50
23/23 [==============================] - 0s 2ms/step - loss: 217.9977
Epoch 37/50
23/23 [==============================] - 0s 2ms/step - loss: 216.9064
Epoch 38/50
23/23 [==============================] - 0s 2ms/step - loss: 215.9083
Epoch 39/50
23/23 [==============================] - 0s 2ms/step - loss: 214.8480
Epoch 40/50
23/23 [==============================] - 0s 2ms/step - loss: 214.3112
Epoch 41/50
23/23 [==============================] - 0s 2ms/step - loss: 213.2117
Epoch 42/50
23/23 [==============================] - 0s 2ms/step - loss: 211.7710
Epoch 43/50
23/23 [==============================] - 0s 2ms/step - loss: 210.8301
Epoch 44/50
23/23 [==============================] - 0s 2ms/step - loss: 209.8952
Epoch 45/50
23/23 [==============================] - 0s 2ms/step - loss: 208.9050
Epoch 46/50
23/23 [==============================] - 0s 2ms/step - loss: 207.9249
Epoch 47/50
23/23 [==============================] - 0s 2ms/step - loss: 207.2522
Epoch 48/50
23/23 [==============================] - 0s 2ms/step - loss: 206.5860
Epoch 49/50
23/23 [==============================] - 0s 2ms/step - loss: 205.3173
Epoch 50/50
23/23 [==============================] - 0s 2ms/step - loss: 204.0305

## Predict and Evaluate

In [19]:
predictions = model.predict(X_test)
print(predictions.shape)
print(y_test.shape)

10/10 [==============================] - 0s 2ms/step
(309, 1)
(309,)

In [20]:
predictions = predictions[0::]
y_test = np.asarray(y_test)
y_test

array([58.8 , 31.35, 50.77, 26.23, 44.61, 37.81, 54.1 , 36.94, 40.87,
       40.86, 24.13, 49.8 , 32.04, 24.  , 79.3 ,  8.06, 44.3 , 24.5 ,
       44.61,  8.54, 26.97, 45.3 , 39.66, 27.42, 37.92, 28.63, 11.17,
       28.8 , 34.24, 64.9 , 71.3 , 50.94, 46.68, 56.14, 43.01, 41.93,
       13.46, 19.77, 45.84, 37.36, 14.64, 28.94, 23.79, 38.6 , 82.6 ,
       64.9 , 22.63, 35.96, 36.8 , 45.37, 28.99, 21.86, 29.55, 24.28,
       71.3 , 23.22, 67.57, 50.53, 76.8 , 53.1 , 18.03, 43.38, 30.14,
       25.37, 20.87, 31.64, 33.95, 17.96, 55.9 , 71.3 , 32.1 , 56.14,
       28.02, 26.2 , 25.45, 39.38, 72.99, 50.46, 34.2 , 39.3 , 42.13,
       28.99, 15.58, 15.09, 26.4 , 14.94, 14.5 , 52.96, 22.14, 32.53,
       61.23, 17.37, 61.07, 52.91, 41.3 , 40.15, 59.8 , 21.92, 24.28,
       45.71, 35.57, 65.2 , 17.57, 66.1 , 55.6 , 66.78, 55.16, 67.11,
       11.47, 26.14, 32.24, 42.13, 31.74, 44.3 , 33.4 ,  4.9 , 59.49,
       29.59, 17.82, 12.18, 52.42, 44.42, 33.49, 10.73, 19.42, 23.35,
       41.54, 55.55, 37.17, 21.16, 40.06, 47.74, 77.3 , 14.99, 43.38,
       45.94, 19.77, 39.32, 24.1 ,  6.9 , 40.27, 33.02, 52.2 , 57.21,
       39.84, 33.7 , 15.52, 46.2 , 15.75, 17.24, 22.93, 18.03, 79.99,
       17.34, 60.95, 19.99, 40.86, 26.74, 43.5 , 15.05, 23.52, 77.3 ,
       22.75, 33.27, 52.3 , 41.67, 29.59, 29.87, 25.62, 10.09, 31.9 ,
       79.3 , 29.45, 15.04,  6.27, 74.5 , 32.11, 65.7 , 71.62, 47.71,
       55.02, 12.46, 33.36, 70.7 , 43.06, 30.12, 37.68, 25.72, 60.32,
       61.46, 19.99, 49.77, 17.6 , 32.33, 31.88, 45.08, 15.57, 39.16,
       68.75, 32.76, 51.02, 33.7 , 25.02, 41.37, 62.5 , 19.01, 39.27,
       40.57, 21.97, 36.99, 52.61, 33.94, 33.42, 17.95, 67.87, 17.2 ,
       53.66, 18.28, 13.29, 19.42, 11.85, 37.72, 33.54, 19.69, 20.77,
       16.26, 77.3 , 45.9 , 25.89, 24.  , 13.29, 42.55, 35.76, 35.3 ,
       20.92, 80.2 , 40.06, 18.13, 33.  , 35.3 , 25.22, 61.24, 40.93,
       23.84, 55.45, 13.36, 14.6 , 22.32, 25.12, 43.25,  7.84, 47.81,
       61.99, 27.68, 15.42, 13.71, 33.12, 24.99, 32.63, 39.  , 71.7 ,
       49.25, 20.08, 14.7 , 42.33, 38.07, 43.57, 10.39, 32.88, 23.52,
       26.86, 41.72, 32.01,  9.01,  4.83, 66.82, 64.02, 22.72, 31.97,
       33.31, 60.28, 38.7 , 52.01, 66.9 , 35.1 , 27.34, 53.3 , 43.7 ,
       39.4 , 31.27, 81.75, 56.63, 33.69, 64.3 , 40.71, 69.84, 23.85,
       38.5 , 55.64, 41.05, 55.9 , 40.66, 74.99, 39.46, 68.3 , 46.93,
       13.52, 29.55, 36.56])

In [21]:
predictions

array([[50.636833],
       [39.607964],
       [33.02435 ],
       [23.96193 ],
       [23.167252],
       [31.414053],
       [44.236286],
       [43.98282 ],
       [33.993134],
       [31.000402],
       [30.806488],
       [37.515476],
       [38.791615],
       [43.130127],
       [41.12051 ],
       [28.453133],
       [31.14406 ],
       [37.66898 ],
       [23.173286],
       [21.219307],
       [22.079596],
       [37.039993],
       [26.607325],
       [32.602596],
       [42.841946],
       [26.971231],
       [35.113575],
       [38.831455],
       [27.77055 ],
       [38.98876 ],
       [40.933525],
       [27.045036],
       [41.042103],
       [44.78263 ],
       [42.58141 ],
       [45.772137],
       [25.6025  ],
       [35.812866],
       [32.346058],
       [28.581715],
       [30.741463],
       [25.894327],
       [26.19042 ],
       [30.763353],
       [43.21564 ],
       [41.367245],
       [32.8631  ],
       [32.635246],
       [35.68469 ],
       [28.417372],
       [22.71816 ],
       [33.17093 ],
       [42.83007 ],
       [28.662188],
       [40.933525],
       [41.825504],
       [51.037003],
       [35.283356],
       [38.3234  ],
       [39.600883],
       [26.038443],
       [27.469236],
       [43.852432],
       [31.281988],
       [36.408974],
       [31.427542],
       [27.899275],
       [25.982132],
       [40.8712  ],
       [40.933525],
       [28.846207],
       [37.822956],
       [30.803793],
       [27.599281],
       [43.942665],
       [48.07609 ],
       [38.219513],
       [37.006744],
       [30.825378],
       [32.76876 ],
       [42.329937],
       [22.718304],
       [38.839714],
       [22.362562],
       [30.572563],
       [26.91469 ],
       [38.01855 ],
       [30.289822],
       [30.319237],
       [29.146555],
       [37.24668 ],
       [30.325272],
       [44.78263 ],
       [39.33376 ],
       [50.479527],
       [32.757015],
       [38.90566 ],
       [32.017086],
       [29.755985],
       [32.941246],
       [28.286777],
       [44.065895],
       [30.378956],
       [37.39198 ],
       [45.776855],
       [38.413338],
       [51.909084],
       [53.811165],
       [44.730244],
       [24.673527],
       [31.915747],
       [45.490177],
       [39.833927],
       [31.789183],
       [29.73726 ],
       [28.888336],
       [38.330235],
       [30.034573],
       [28.864988],
       [25.798073],
       [37.51417 ],
       [44.699528],
       [43.8281  ],
       [29.484509],
       [30.097347],
       [44.625324],
       [30.186153],
       [43.89043 ],
       [31.03619 ],
       [40.934826],
       [32.402863],
       [31.537243],
       [41.01663 ],
       [37.485096],
       [36.060677],
       [30.399473],
       [36.47597 ],
       [29.164558],
       [39.036976],
       [27.825075],
       [36.763874],
       [36.0456  ],
       [30.804905],
       [36.20846 ],
       [20.57057 ],
       [36.43269 ],
       [26.547546],
       [41.117928],
       [27.836946],
       [35.01741 ],
       [23.411255],
       [26.050001],
       [53.410473],
       [35.175907],
       [33.984238],
       [23.091675],
       [41.820946],
       [37.057865],
       [29.296986],
       [41.276203],
       [35.037006],
       [41.01663 ],
       [40.92438 ],
       [32.543316],
       [46.1699  ],
       [40.97977 ],
       [38.23497 ],
       [21.540855],
       [41.268723],
       [24.582392],
       [40.99747 ],
       [41.12051 ],
       [30.432951],
       [30.49836 ],
       [41.807693],
       [43.028656],
       [39.480038],
       [39.378086],
       [54.935055],
       [33.241096],
       [26.980251],
       [25.548859],
       [34.154613],
       [46.794094],
       [41.52398 ],
       [34.104153],
       [27.691532],
       [30.118015],
       [34.61942 ],
       [41.125206],
       [23.121052],
       [32.451138],
       [31.892126],
       [35.898445],
       [31.800499],
       [35.14935 ],
       [24.600914],
       [27.812103],
       [38.413338],
       [28.67308 ],
       [49.10238 ],
       [30.357918],
       [44.625324],
       [47.71164 ],
       [42.097656],
       [28.540874],
       [32.62642 ],
       [30.786259],
       [26.962027],
       [35.45572 ],
       [54.421593],
       [34.196167],
       [34.553513],
       [25.976658],
       [30.803001],
       [30.693115],
       [27.20259 ],
       [28.548138],
       [23.163017],
       [26.692352],
       [38.20064 ],
       [36.22962 ],
       [27.437374],
       [36.448166],
       [37.74227 ],
       [38.837845],
       [41.01663 ],
       [40.942703],
       [35.99835 ],
       [43.156693],
       [23.142788],
       [31.510647],
       [38.458862],
       [40.85933 ],
       [30.700722],
       [37.660908],
       [32.387993],
       [41.28222 ],
       [30.795225],
       [40.85933 ],
       [38.75392 ],
       [37.21563 ],
       [36.411896],
       [31.522675],
       [39.99702 ],
       [30.712505],
       [35.268017],
       [30.745153],
       [38.256027],
       [30.688646],
       [33.853573],
       [34.495712],
       [32.759907],
       [25.356018],
       [23.897058],
       [36.385838],
       [30.412083],
       [30.076462],
       [30.755444],
       [39.232647],
       [43.8125  ],
       [33.484463],
       [30.81205 ],
       [41.813633],
       [27.698685],
       [30.987808],
       [28.083294],
       [26.360975],
       [32.67353 ],
       [25.32584 ],
       [27.45473 ],
       [31.254934],
       [40.446068],
       [41.485554],
       [26.349106],
       [37.49837 ],
       [48.805542],
       [30.432169],
       [41.310276],
       [21.435247],
       [49.254627],
       [38.5479  ],
       [44.637203],
       [46.607105],
       [39.04885 ],
       [39.423954],
       [39.86801 ],
       [42.863373],
       [23.607086],
       [29.21388 ],
       [42.038784],
       [31.018608],
       [33.971783],
       [43.962013],
       [30.563547],
       [50.74255 ],
       [41.433712],
       [31.913342],
       [34.89232 ],
       [38.045803],
       [40.8712  ],
       [41.731903],
       [51.209282],
       [29.660305],
       [45.839184],
       [27.965809],
       [36.804245],
       [26.789782],
       [27.682388]], dtype=float32)

In [22]:
print("Mean absolute error: %.2f" % np.mean(np.absolute(predictions - y_test)))
print("Residual sum of squares (MSE): %.2f" % np.mean((predictions - y_test) ** 2))
from sklearn.metrics import r2_score
print("R2-score: %.2f" % r2_score(y_test, predictions) )

Mean absolute error: 15.62
Residual sum of squares (MSE): 381.76
R2-score: 0.21

# Increasing hidden layers didn't reduce the MSE in this case!