In [1]:
# Concrete

## Import Necessary Libraries

In [2]:
import pandas as pd
import numpy as np

import keras
from keras.models import Sequential
from keras.layers import Dense

## Import Data

In [18]:
df = pd.read_csv("https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv")
df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

## Data info

In [4]:
df.shape

(1030, 9)

In [5]:
df.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [6]:
df.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

## Split Predictors and Target values

In [7]:
concrete_data_columns = df.columns

X = df.drop('Strength', 1).values # all columns except Strength
y = df['Strength'] # Strength column

C:\Users\Maxter\AppData\Local\Temp/ipykernel_13948/464899849.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X = df.drop('Strength', 1).values # all columns except Strength

## Normalize Data (new!!)

In [8]:
X_norm = (X - X.mean()) / X.std()

## Split data into Train and Test sets

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_norm, y, test_size = 0.3, random_state=6)

In [10]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(721, 8)
(309, 8)
(721,)
(309,)

## Build and Train Neural Network

In [11]:
n_cols = X.shape[1]
n_cols

8

In [12]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    # model.add(Dense(10, activation='relu'))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [13]:
# build the model
model = regression_model()

# train
np.random.seed(45)
model.fit(X_train, y_train, epochs=100, verbose=1)

Epoch 1/100
23/23 [==============================] - 1s 2ms/step - loss: 1474.4584
Epoch 2/100
23/23 [==============================] - 0s 2ms/step - loss: 1433.2775
Epoch 3/100
23/23 [==============================] - 0s 2ms/step - loss: 1388.2435
Epoch 4/100
23/23 [==============================] - 0s 2ms/step - loss: 1342.2179
Epoch 5/100
23/23 [==============================] - 0s 2ms/step - loss: 1296.8109
Epoch 6/100
23/23 [==============================] - 0s 2ms/step - loss: 1250.9034
Epoch 7/100
23/23 [==============================] - 0s 2ms/step - loss: 1204.8051
Epoch 8/100
23/23 [==============================] - 0s 2ms/step - loss: 1155.7118
Epoch 9/100
23/23 [==============================] - 0s 2ms/step - loss: 1101.4044
Epoch 10/100
23/23 [==============================] - 0s 2ms/step - loss: 1043.9589
Epoch 11/100
23/23 [==============================] - 0s 2ms/step - loss: 985.2743
Epoch 12/100
23/23 [==============================] - 0s 2ms/step - loss: 924.5615
Epoch 13/100
23/23 [==============================] - 0s 2ms/step - loss: 864.5963
Epoch 14/100
23/23 [==============================] - 0s 2ms/step - loss: 805.3619
Epoch 15/100
23/23 [==============================] - 0s 2ms/step - loss: 747.5057
Epoch 16/100
23/23 [==============================] - 0s 2ms/step - loss: 692.6714
Epoch 17/100
23/23 [==============================] - 0s 2ms/step - loss: 640.5294
Epoch 18/100
23/23 [==============================] - 0s 2ms/step - loss: 591.4033
Epoch 19/100
23/23 [==============================] - 0s 2ms/step - loss: 546.4055
Epoch 20/100
23/23 [==============================] - 0s 2ms/step - loss: 505.2263
Epoch 21/100
23/23 [==============================] - 0s 2ms/step - loss: 467.8863
Epoch 22/100
23/23 [==============================] - 0s 2ms/step - loss: 434.3543
Epoch 23/100
23/23 [==============================] - 0s 2ms/step - loss: 405.6909
Epoch 24/100
23/23 [==============================] - 0s 2ms/step - loss: 380.7765
Epoch 25/100
23/23 [==============================] - 0s 2ms/step - loss: 359.5213
Epoch 26/100
23/23 [==============================] - 0s 2ms/step - loss: 341.0390
Epoch 27/100
23/23 [==============================] - 0s 2ms/step - loss: 326.4041
Epoch 28/100
23/23 [==============================] - 0s 2ms/step - loss: 314.0876
Epoch 29/100
23/23 [==============================] - 0s 2ms/step - loss: 304.2484
Epoch 30/100
23/23 [==============================] - 0s 2ms/step - loss: 296.0243
Epoch 31/100
23/23 [==============================] - 0s 2ms/step - loss: 290.1354
Epoch 32/100
23/23 [==============================] - 0s 2ms/step - loss: 284.7315
Epoch 33/100
23/23 [==============================] - 0s 2ms/step - loss: 280.8689
Epoch 34/100
23/23 [==============================] - 0s 2ms/step - loss: 277.7292
Epoch 35/100
23/23 [==============================] - 0s 2ms/step - loss: 275.3698
Epoch 36/100
23/23 [==============================] - 0s 2ms/step - loss: 273.2306
Epoch 37/100
23/23 [==============================] - 0s 2ms/step - loss: 271.6811
Epoch 38/100
23/23 [==============================] - 0s 2ms/step - loss: 270.3406
Epoch 39/100
23/23 [==============================] - 0s 2ms/step - loss: 269.2078
Epoch 40/100
23/23 [==============================] - 0s 2ms/step - loss: 268.2186
Epoch 41/100
23/23 [==============================] - 0s 2ms/step - loss: 267.3487
Epoch 42/100
23/23 [==============================] - 0s 2ms/step - loss: 266.4750
Epoch 43/100
23/23 [==============================] - 0s 3ms/step - loss: 265.7382
Epoch 44/100
23/23 [==============================] - 0s 2ms/step - loss: 264.9810
Epoch 45/100
23/23 [==============================] - 0s 3ms/step - loss: 264.3033
Epoch 46/100
23/23 [==============================] - 0s 3ms/step - loss: 263.6263
Epoch 47/100
23/23 [==============================] - 0s 2ms/step - loss: 262.9545
Epoch 48/100
23/23 [==============================] - 0s 2ms/step - loss: 262.3458
Epoch 49/100
23/23 [==============================] - 0s 2ms/step - loss: 261.6708
Epoch 50/100
23/23 [==============================] - 0s 2ms/step - loss: 261.0575
Epoch 51/100
23/23 [==============================] - 0s 1ms/step - loss: 260.4032
Epoch 52/100
23/23 [==============================] - 0s 2ms/step - loss: 259.7917
Epoch 53/100
23/23 [==============================] - 0s 2ms/step - loss: 259.2175
Epoch 54/100
23/23 [==============================] - 0s 1ms/step - loss: 258.6249
Epoch 55/100
23/23 [==============================] - 0s 2ms/step - loss: 258.0706
Epoch 56/100
23/23 [==============================] - 0s 2ms/step - loss: 257.5094
Epoch 57/100
23/23 [==============================] - 0s 1ms/step - loss: 256.9754
Epoch 58/100
23/23 [==============================] - 0s 2ms/step - loss: 256.3251
Epoch 59/100
23/23 [==============================] - 0s 2ms/step - loss: 255.7342
Epoch 60/100
23/23 [==============================] - 0s 1ms/step - loss: 255.1956
Epoch 61/100
23/23 [==============================] - 0s 2ms/step - loss: 254.6048
Epoch 62/100
23/23 [==============================] - 0s 2ms/step - loss: 254.0468
Epoch 63/100
23/23 [==============================] - 0s 1ms/step - loss: 253.4944
Epoch 64/100
23/23 [==============================] - 0s 1ms/step - loss: 252.9580
Epoch 65/100
23/23 [==============================] - 0s 2ms/step - loss: 252.4409
Epoch 66/100
23/23 [==============================] - 0s 2ms/step - loss: 251.8780
Epoch 67/100
23/23 [==============================] - 0s 2ms/step - loss: 251.3298
Epoch 68/100
23/23 [==============================] - 0s 2ms/step - loss: 250.8024
Epoch 69/100
23/23 [==============================] - 0s 1ms/step - loss: 250.2839
Epoch 70/100
23/23 [==============================] - 0s 2ms/step - loss: 249.7142
Epoch 71/100
23/23 [==============================] - 0s 2ms/step - loss: 249.2690
Epoch 72/100
23/23 [==============================] - 0s 1ms/step - loss: 248.7017
Epoch 73/100
23/23 [==============================] - 0s 1ms/step - loss: 248.1664
Epoch 74/100
23/23 [==============================] - 0s 2ms/step - loss: 247.6461
Epoch 75/100
23/23 [==============================] - 0s 2ms/step - loss: 247.1354
Epoch 76/100
23/23 [==============================] - 0s 2ms/step - loss: 246.7167
Epoch 77/100
23/23 [==============================] - 0s 2ms/step - loss: 246.0773
Epoch 78/100
23/23 [==============================] - 0s 2ms/step - loss: 245.5939
Epoch 79/100
23/23 [==============================] - 0s 1ms/step - loss: 245.1170
Epoch 80/100
23/23 [==============================] - 0s 1ms/step - loss: 244.6277
Epoch 81/100
23/23 [==============================] - 0s 2ms/step - loss: 244.0755
Epoch 82/100
23/23 [==============================] - 0s 2ms/step - loss: 243.5835
Epoch 83/100
23/23 [==============================] - 0s 2ms/step - loss: 243.0971
Epoch 84/100
23/23 [==============================] - 0s 2ms/step - loss: 242.6220
Epoch 85/100
23/23 [==============================] - 0s 1ms/step - loss: 242.1375
Epoch 86/100
23/23 [==============================] - 0s 2ms/step - loss: 241.7740
Epoch 87/100
23/23 [==============================] - 0s 2ms/step - loss: 241.1337
Epoch 88/100
23/23 [==============================] - 0s 1ms/step - loss: 240.7090
Epoch 89/100
23/23 [==============================] - 0s 2ms/step - loss: 240.2124
Epoch 90/100
23/23 [==============================] - 0s 2ms/step - loss: 239.7422
Epoch 91/100
23/23 [==============================] - 0s 2ms/step - loss: 239.2621
Epoch 92/100
23/23 [==============================] - 0s 2ms/step - loss: 238.7797
Epoch 93/100
23/23 [==============================] - 0s 2ms/step - loss: 238.4879
Epoch 94/100
23/23 [==============================] - 0s 2ms/step - loss: 237.7925
Epoch 95/100
23/23 [==============================] - 0s 1ms/step - loss: 237.3477
Epoch 96/100
23/23 [==============================] - 0s 2ms/step - loss: 236.8633
Epoch 97/100
23/23 [==============================] - 0s 2ms/step - loss: 236.4170
Epoch 98/100
23/23 [==============================] - 0s 2ms/step - loss: 235.9868
Epoch 99/100

23/23 [==============================] - 0s 2ms/step - loss: 235.5766
Epoch 100/100
23/23 [==============================] - 0s 2ms/step - loss: 234.9976

## Predict and Evaluate

In [14]:
predictions = model.predict(X_test)
print(predictions.shape)
print(y_test.shape)

10/10 [==============================] - 0s 2ms/step
(309, 1)
(309,)

In [15]:
predictions = predictions[0::]
y_test = np.asarray(y_test)
y_test

array([58.8 , 31.35, 50.77, 26.23, 44.61, 37.81, 54.1 , 36.94, 40.87,
       40.86, 24.13, 49.8 , 32.04, 24.  , 79.3 ,  8.06, 44.3 , 24.5 ,
       44.61,  8.54, 26.97, 45.3 , 39.66, 27.42, 37.92, 28.63, 11.17,
       28.8 , 34.24, 64.9 , 71.3 , 50.94, 46.68, 56.14, 43.01, 41.93,
       13.46, 19.77, 45.84, 37.36, 14.64, 28.94, 23.79, 38.6 , 82.6 ,
       64.9 , 22.63, 35.96, 36.8 , 45.37, 28.99, 21.86, 29.55, 24.28,
       71.3 , 23.22, 67.57, 50.53, 76.8 , 53.1 , 18.03, 43.38, 30.14,
       25.37, 20.87, 31.64, 33.95, 17.96, 55.9 , 71.3 , 32.1 , 56.14,
       28.02, 26.2 , 25.45, 39.38, 72.99, 50.46, 34.2 , 39.3 , 42.13,
       28.99, 15.58, 15.09, 26.4 , 14.94, 14.5 , 52.96, 22.14, 32.53,
       61.23, 17.37, 61.07, 52.91, 41.3 , 40.15, 59.8 , 21.92, 24.28,
       45.71, 35.57, 65.2 , 17.57, 66.1 , 55.6 , 66.78, 55.16, 67.11,
       11.47, 26.14, 32.24, 42.13, 31.74, 44.3 , 33.4 ,  4.9 , 59.49,
       29.59, 17.82, 12.18, 52.42, 44.42, 33.49, 10.73, 19.42, 23.35,
       41.54, 55.55, 37.17, 21.16, 40.06, 47.74, 77.3 , 14.99, 43.38,
       45.94, 19.77, 39.32, 24.1 ,  6.9 , 40.27, 33.02, 52.2 , 57.21,
       39.84, 33.7 , 15.52, 46.2 , 15.75, 17.24, 22.93, 18.03, 79.99,
       17.34, 60.95, 19.99, 40.86, 26.74, 43.5 , 15.05, 23.52, 77.3 ,
       22.75, 33.27, 52.3 , 41.67, 29.59, 29.87, 25.62, 10.09, 31.9 ,
       79.3 , 29.45, 15.04,  6.27, 74.5 , 32.11, 65.7 , 71.62, 47.71,
       55.02, 12.46, 33.36, 70.7 , 43.06, 30.12, 37.68, 25.72, 60.32,
       61.46, 19.99, 49.77, 17.6 , 32.33, 31.88, 45.08, 15.57, 39.16,
       68.75, 32.76, 51.02, 33.7 , 25.02, 41.37, 62.5 , 19.01, 39.27,
       40.57, 21.97, 36.99, 52.61, 33.94, 33.42, 17.95, 67.87, 17.2 ,
       53.66, 18.28, 13.29, 19.42, 11.85, 37.72, 33.54, 19.69, 20.77,
       16.26, 77.3 , 45.9 , 25.89, 24.  , 13.29, 42.55, 35.76, 35.3 ,
       20.92, 80.2 , 40.06, 18.13, 33.  , 35.3 , 25.22, 61.24, 40.93,
       23.84, 55.45, 13.36, 14.6 , 22.32, 25.12, 43.25,  7.84, 47.81,
       61.99, 27.68, 15.42, 13.71, 33.12, 24.99, 32.63, 39.  , 71.7 ,
       49.25, 20.08, 14.7 , 42.33, 38.07, 43.57, 10.39, 32.88, 23.52,
       26.86, 41.72, 32.01,  9.01,  4.83, 66.82, 64.02, 22.72, 31.97,
       33.31, 60.28, 38.7 , 52.01, 66.9 , 35.1 , 27.34, 53.3 , 43.7 ,
       39.4 , 31.27, 81.75, 56.63, 33.69, 64.3 , 40.71, 69.84, 23.85,
       38.5 , 55.64, 41.05, 55.9 , 40.66, 74.99, 39.46, 68.3 , 46.93,
       13.52, 29.55, 36.56])

In [16]:
predictions

array([[44.785404],
       [38.25519 ],
       [33.95464 ],
       [27.909927],
       [26.850746],
       [29.804777],
       [40.681473],
       [41.00812 ],
       [34.2183  ],
       [32.77125 ],
       [32.94538 ],
       [33.2008  ],
       [38.382812],
       [40.780643],
       [36.407955],
       [30.788769],
       [33.470882],
       [38.360584],
       [26.867386],
       [26.841036],
       [25.938972],
       [35.6537  ],
       [28.504637],
       [34.217308],
       [38.306454],
       [29.22498 ],
       [37.440002],
       [34.21526 ],
       [30.02076 ],
       [33.885063],
       [36.80045 ],
       [29.120369],
       [38.96841 ],
       [39.95005 ],
       [36.33106 ],
       [37.88281 ],
       [29.712078],
       [34.30145 ],
       [33.77793 ],
       [29.429785],
       [32.93811 ],
       [28.90607 ],
       [29.668985],
       [32.90949 ],
       [37.514374],
       [36.471302],
       [33.68629 ],
       [34.148777],
       [35.395367],
       [31.392282],
       [25.606941],
       [35.88495 ],
       [38.331375],
       [32.050613],
       [36.80045 ],
       [40.06688 ],
       [45.48753 ],
       [33.032707],
       [35.398514],
       [36.61982 ],
       [30.35849 ],
       [28.81931 ],
       [41.129562],
       [34.79911 ],
       [37.82365 ],
       [34.79179 ],
       [28.788315],
       [31.148926],
       [36.931286],
       [36.80045 ],
       [31.664345],
       [33.752354],
       [32.80728 ],
       [32.49511 ],
       [41.155804],
       [41.745342],
       [35.61657 ],
       [35.46564 ],
       [33.31057 ],
       [33.05377 ],
       [38.005936],
       [25.612019],
       [39.005898],
       [28.35627 ],
       [33.706104],
       [29.565432],
       [38.507847],
       [32.26105 ],
       [33.67932 ],
       [31.321558],
       [35.245205],
       [33.107754],
       [39.95005 ],
       [37.18053 ],
       [45.115604],
       [33.708996],
       [34.059505],
       [29.778358],
       [33.93997 ],
       [34.129086],
       [31.666409],
       [39.680153],
       [33.153553],
       [35.036346],
       [40.261806],
       [36.781868],
       [42.55225 ],
       [43.608757],
       [42.03543 ],
       [28.33273 ],
       [33.756447],
       [38.47467 ],
       [39.339165],
       [30.738876],
       [31.63956 ],
       [31.863577],
       [36.956314],
       [32.79684 ],
       [32.126247],
       [31.04764 ],
       [35.19874 ],
       [40.124496],
       [38.891254],
       [31.506563],
       [33.460274],
       [40.280247],
       [31.406036],
       [38.76042 ],
       [31.303846],
       [39.805626],
       [33.352783],
       [34.263317],
       [36.626007],
       [38.344757],
       [33.212063],
       [32.952   ],
       [37.636765],
       [29.042027],
       [35.96944 ],
       [28.944067],
       [32.043835],
       [33.55153 ],
       [32.82227 ],
       [34.536804],
       [23.262901],
       [35.106216],
       [30.02782 ],
       [36.994633],
       [28.91915 ],
       [34.1473  ],
       [26.43365 ],
       [30.361752],
       [45.638172],
       [37.309174],
       [35.459133],
       [27.915495],
       [39.645756],
       [36.508453],
       [31.964287],
       [40.238712],
       [33.54981 ],
       [36.626007],
       [39.074062],
       [34.157566],
       [42.1587  ],
       [39.099243],
       [37.00742 ],
       [25.81077 ],
       [39.606228],
       [29.468822],
       [39.672264],
       [36.407955],
       [33.617798],
       [33.86186 ],
       [40.104263],
       [37.90687 ],
       [37.09244 ],
       [36.561172],
       [44.999363],
       [32.20589 ],
       [28.835066],
       [29.970448],
       [36.33486 ],
       [40.594547],
       [39.070435],
       [34.540108],
       [31.28808 ],
       [34.096058],
       [35.636097],
       [38.793964],
       [27.921768],
       [32.98226 ],
       [33.394157],
       [36.22764 ],
       [33.2425  ],
       [36.10061 ],
       [29.62976 ],
       [29.93354 ],
       [36.781868],
       [30.76891 ],
       [43.701767],
       [33.039223],
       [40.280247],
       [42.865902],
       [39.619267],
       [31.524483],
       [33.98312 ],
       [33.257534],
       [30.944618],
       [35.8071  ],
       [46.077175],
       [36.247643],
       [33.5743  ],
       [31.144337],
       [31.053957],
       [30.094967],
       [28.961111],
       [30.220396],
       [29.10389 ],
       [29.439386],
       [38.718906],
       [33.16526 ],
       [30.923615],
       [37.624218],
       [38.041622],
       [38.903206],
       [36.626007],
       [39.05656 ],
       [33.342896],
       [40.8015  ],
       [29.093964],
       [34.617348],
       [38.176884],
       [36.956203],
       [33.57223 ],
       [32.895527],
       [33.342484],
       [40.20517 ],
       [32.116463],
       [36.956203],
       [38.665733],
       [35.223858],
       [35.74295 ],
       [32.8844  ],
       [38.72989 ],
       [33.375576],
       [37.3524  ],
       [33.30704 ],
       [37.112064],
       [32.10796 ],
       [36.903076],
       [34.13702 ],
       [33.88711 ],
       [28.053102],
       [29.682632],
       [37.75505 ],
       [28.87804 ],
       [34.183277],
       [29.964132],
       [36.866447],
       [37.63918 ],
       [32.63952 ],
       [33.363148],
       [40.0918  ],
       [28.606083],
       [32.421013],
       [28.402046],
       [29.02174 ],
       [32.94233 ],
       [29.061947],
       [28.68457 ],
       [31.860298],
       [37.66382 ],
       [40.34976 ],
       [29.04666 ],
       [36.336742],
       [42.243618],
       [33.71085 ],
       [39.51901 ],
       [24.835615],
       [44.091618],
       [37.989983],
       [40.25533 ],
       [40.98704 ],
       [35.94452 ],
       [38.64146 ],
       [36.059105],
       [35.739197],
       [28.111677],
       [32.138733],
       [38.6546  ],
       [32.3737  ],
       [32.06022 ],
       [39.898205],
       [33.343674],
       [44.132267],
       [38.898952],
       [34.383434],
       [35.74275 ],
       [35.581024],
       [36.931286],
       [39.83266 ],
       [45.67506 ],
       [29.970055],
       [40.130974],
       [28.045372],
       [37.653584],
       [29.656158],
       [32.32066 ]], dtype=float32)

In [17]:
print("Mean absolute error: %.2f" % np.mean(np.absolute(predictions - y_test)))
print("Residual sum of squares (MSE): %.2f" % np.mean((predictions - y_test) ** 2))
from sklearn.metrics import r2_score
print("R2-score: %.2f" % r2_score(y_test, predictions) )

Mean absolute error: 14.94
Residual sum of squares (MSE): 350.75
R2-score: 0.08

# With data normalization, MSE decreased from 391.12 to 350.75 !