In [1]:
# Concrete

## Import Necessary Libraries

In [2]:
import pandas as pd
import numpy as np

import keras
from keras.models import Sequential
from keras.layers import Dense

## Import Data

In [20]:
df = pd.read_csv("https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv")
df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

## Data info

In [21]:
df.shape

(1030, 9)

In [5]:
df.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [6]:
df.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

## Split Predictors and Target values

In [7]:
concrete_data_columns = df.columns

X = df.drop('Strength', 1).values # all columns except Strength
y = df['Strength'] # Strength column

C:\Users\Maxter\AppData\Local\Temp/ipykernel_3684/464899849.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X = df.drop('Strength', 1).values # all columns except Strength

## Split data into Train and Test sets

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=6)

In [9]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(721, 8)
(309, 8)
(721,)
(309,)

## Build and Train Neural Network

In [10]:
n_cols = X.shape[1]
n_cols

8

In [11]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    # model.add(Dense(10, activation='relu'))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [16]:
# build the model
model = regression_model()

# train
np.random.seed(45)
model.fit(X_train, y_train, epochs=50, verbose=1)

Epoch 1/50
23/23 [==============================] - 0s 2ms/step - loss: 44801.4492
Epoch 2/50
23/23 [==============================] - 0s 2ms/step - loss: 10697.3047
Epoch 3/50
23/23 [==============================] - 0s 2ms/step - loss: 5722.0005
Epoch 4/50
23/23 [==============================] - 0s 2ms/step - loss: 5129.2817
Epoch 5/50
23/23 [==============================] - 0s 1ms/step - loss: 4301.3379
Epoch 6/50
23/23 [==============================] - 0s 2ms/step - loss: 3211.3218
Epoch 7/50
23/23 [==============================] - 0s 2ms/step - loss: 2267.9082
Epoch 8/50
23/23 [==============================] - 0s 2ms/step - loss: 1706.4724
Epoch 9/50
23/23 [==============================] - 0s 2ms/step - loss: 1384.2729
Epoch 10/50
23/23 [==============================] - 0s 2ms/step - loss: 1153.5594
Epoch 11/50
23/23 [==============================] - 0s 2ms/step - loss: 995.5233
Epoch 12/50
23/23 [==============================] - 0s 2ms/step - loss: 865.3815
Epoch 13/50
23/23 [==============================] - 0s 1ms/step - loss: 774.5883
Epoch 14/50
23/23 [==============================] - 0s 2ms/step - loss: 697.9462
Epoch 15/50
23/23 [==============================] - 0s 2ms/step - loss: 624.7399
Epoch 16/50
23/23 [==============================] - 0s 2ms/step - loss: 565.4298
Epoch 17/50
23/23 [==============================] - 0s 2ms/step - loss: 518.6363
Epoch 18/50
23/23 [==============================] - 0s 2ms/step - loss: 477.9902
Epoch 19/50
23/23 [==============================] - 0s 2ms/step - loss: 443.5469
Epoch 20/50
23/23 [==============================] - 0s 2ms/step - loss: 411.2497
Epoch 21/50
23/23 [==============================] - 0s 2ms/step - loss: 382.6808
Epoch 22/50
23/23 [==============================] - 0s 2ms/step - loss: 359.7444
Epoch 23/50
23/23 [==============================] - 0s 2ms/step - loss: 342.4505
Epoch 24/50
23/23 [==============================] - 0s 2ms/step - loss: 322.0049
Epoch 25/50
23/23 [==============================] - 0s 2ms/step - loss: 306.6286
Epoch 26/50
23/23 [==============================] - 0s 2ms/step - loss: 295.5142
Epoch 27/50
23/23 [==============================] - 0s 2ms/step - loss: 286.5673
Epoch 28/50
23/23 [==============================] - 0s 2ms/step - loss: 275.0879
Epoch 29/50
23/23 [==============================] - 0s 2ms/step - loss: 267.0652
Epoch 30/50
23/23 [==============================] - 0s 2ms/step - loss: 255.5580
Epoch 31/50
23/23 [==============================] - 0s 2ms/step - loss: 247.5081
Epoch 32/50
23/23 [==============================] - 0s 2ms/step - loss: 242.4556
Epoch 33/50
23/23 [==============================] - 0s 2ms/step - loss: 239.9976
Epoch 34/50
23/23 [==============================] - 0s 2ms/step - loss: 230.1945
Epoch 35/50
23/23 [==============================] - 0s 2ms/step - loss: 225.4833
Epoch 36/50
23/23 [==============================] - 0s 2ms/step - loss: 218.4378
Epoch 37/50
23/23 [==============================] - 0s 2ms/step - loss: 212.3053
Epoch 38/50
23/23 [==============================] - 0s 2ms/step - loss: 205.2097
Epoch 39/50
23/23 [==============================] - 0s 2ms/step - loss: 199.5116
Epoch 40/50
23/23 [==============================] - 0s 2ms/step - loss: 194.5406
Epoch 41/50
23/23 [==============================] - 0s 2ms/step - loss: 191.2552
Epoch 42/50
23/23 [==============================] - 0s 2ms/step - loss: 187.6017
Epoch 43/50
23/23 [==============================] - 0s 2ms/step - loss: 182.0325
Epoch 44/50
23/23 [==============================] - 0s 2ms/step - loss: 177.7125
Epoch 45/50
23/23 [==============================] - 0s 2ms/step - loss: 172.9025
Epoch 46/50
23/23 [==============================] - 0s 2ms/step - loss: 171.0705
Epoch 47/50
23/23 [==============================] - 0s 2ms/step - loss: 165.8624
Epoch 48/50
23/23 [==============================] - 0s 2ms/step - loss: 164.7511
Epoch 49/50
23/23 [==============================] - 0s 2ms/step - loss: 161.0261
Epoch 50/50
23/23 [==============================] - 0s 2ms/step - loss: 159.8909

## Predict and Evaluate

In [17]:
predictions = model.predict(X_test)
print(predictions.shape)
print(y_test.shape)
y_test = np.asarray(y_test)
y_test

10/10 [==============================] - 0s 2ms/step
(309, 1)
(309,)

array([58.8 , 31.35, 50.77, 26.23, 44.61, 37.81, 54.1 , 36.94, 40.87,
       40.86, 24.13, 49.8 , 32.04, 24.  , 79.3 ,  8.06, 44.3 , 24.5 ,
       44.61,  8.54, 26.97, 45.3 , 39.66, 27.42, 37.92, 28.63, 11.17,
       28.8 , 34.24, 64.9 , 71.3 , 50.94, 46.68, 56.14, 43.01, 41.93,
       13.46, 19.77, 45.84, 37.36, 14.64, 28.94, 23.79, 38.6 , 82.6 ,
       64.9 , 22.63, 35.96, 36.8 , 45.37, 28.99, 21.86, 29.55, 24.28,
       71.3 , 23.22, 67.57, 50.53, 76.8 , 53.1 , 18.03, 43.38, 30.14,
       25.37, 20.87, 31.64, 33.95, 17.96, 55.9 , 71.3 , 32.1 , 56.14,
       28.02, 26.2 , 25.45, 39.38, 72.99, 50.46, 34.2 , 39.3 , 42.13,
       28.99, 15.58, 15.09, 26.4 , 14.94, 14.5 , 52.96, 22.14, 32.53,
       61.23, 17.37, 61.07, 52.91, 41.3 , 40.15, 59.8 , 21.92, 24.28,
       45.71, 35.57, 65.2 , 17.57, 66.1 , 55.6 , 66.78, 55.16, 67.11,
       11.47, 26.14, 32.24, 42.13, 31.74, 44.3 , 33.4 ,  4.9 , 59.49,
       29.59, 17.82, 12.18, 52.42, 44.42, 33.49, 10.73, 19.42, 23.35,
       41.54, 55.55, 37.17, 21.16, 40.06, 47.74, 77.3 , 14.99, 43.38,
       45.94, 19.77, 39.32, 24.1 ,  6.9 , 40.27, 33.02, 52.2 , 57.21,
       39.84, 33.7 , 15.52, 46.2 , 15.75, 17.24, 22.93, 18.03, 79.99,
       17.34, 60.95, 19.99, 40.86, 26.74, 43.5 , 15.05, 23.52, 77.3 ,
       22.75, 33.27, 52.3 , 41.67, 29.59, 29.87, 25.62, 10.09, 31.9 ,
       79.3 , 29.45, 15.04,  6.27, 74.5 , 32.11, 65.7 , 71.62, 47.71,
       55.02, 12.46, 33.36, 70.7 , 43.06, 30.12, 37.68, 25.72, 60.32,
       61.46, 19.99, 49.77, 17.6 , 32.33, 31.88, 45.08, 15.57, 39.16,
       68.75, 32.76, 51.02, 33.7 , 25.02, 41.37, 62.5 , 19.01, 39.27,
       40.57, 21.97, 36.99, 52.61, 33.94, 33.42, 17.95, 67.87, 17.2 ,
       53.66, 18.28, 13.29, 19.42, 11.85, 37.72, 33.54, 19.69, 20.77,
       16.26, 77.3 , 45.9 , 25.89, 24.  , 13.29, 42.55, 35.76, 35.3 ,
       20.92, 80.2 , 40.06, 18.13, 33.  , 35.3 , 25.22, 61.24, 40.93,
       23.84, 55.45, 13.36, 14.6 , 22.32, 25.12, 43.25,  7.84, 47.81,
       61.99, 27.68, 15.42, 13.71, 33.12, 24.99, 32.63, 39.  , 71.7 ,
       49.25, 20.08, 14.7 , 42.33, 38.07, 43.57, 10.39, 32.88, 23.52,
       26.86, 41.72, 32.01,  9.01,  4.83, 66.82, 64.02, 22.72, 31.97,
       33.31, 60.28, 38.7 , 52.01, 66.9 , 35.1 , 27.34, 53.3 , 43.7 ,
       39.4 , 31.27, 81.75, 56.63, 33.69, 64.3 , 40.71, 69.84, 23.85,
       38.5 , 55.64, 41.05, 55.9 , 40.66, 74.99, 39.46, 68.3 , 46.93,
       13.52, 29.55, 36.56])

In [18]:
predictions

array([[54.86306  ],
       [46.30284  ],
       [33.567257 ],
       [28.659624 ],
       [32.960304 ],
       [25.109518 ],
       [34.167915 ],
       [35.35664  ],
       [55.113922 ],
       [49.55155  ],
       [30.770933 ],
       [52.892384 ],
       [32.778996 ],
       [30.791746 ],
       [49.538296 ],
       [11.006459 ],
       [46.139484 ],
       [18.507261 ],
       [32.652885 ],
       [46.677105 ],
       [34.467487 ],
       [39.63796  ],
       [37.706676 ],
       [16.311895 ],
       [35.457066 ],
       [57.45821  ],
       [ 6.5410743],
       [48.15701  ],
       [22.286558 ],
       [52.025555 ],
       [46.67979  ],
       [47.651157 ],
       [41.114086 ],
       [50.950512 ],
       [63.784348 ],
       [73.698555 ],
       [33.450066 ],
       [26.71565  ],
       [42.72944  ],
       [35.75394  ],
       [15.597905 ],
       [24.445623 ],
       [30.676199 ],
       [22.021574 ],
       [58.970707 ],
       [50.74384  ],
       [19.984304 ],
       [18.915369 ],
       [41.421947 ],
       [39.13964  ],
       [42.722675 ],
       [32.441216 ],
       [34.155174 ],
       [16.969812 ],
       [46.67979  ],
       [30.222422 ],
       [34.49396  ],
       [37.768696 ],
       [40.0796   ],
       [57.07078  ],
       [32.061913 ],
       [38.169216 ],
       [33.26388  ],
       [15.956544 ],
       [15.046018 ],
       [16.958483 ],
       [31.347105 ],
       [24.750578 ],
       [43.77695  ],
       [46.67979  ],
       [31.643984 ],
       [63.103275 ],
       [20.56816  ],
       [ 3.9751217],
       [33.184254 ],
       [40.474392 ],
       [38.598766 ],
       [50.62556  ],
       [30.984285 ],
       [34.3865   ],
       [52.221085 ],
       [42.470177 ],
       [17.071661 ],
       [33.526787 ],
       [17.898825 ],
       [23.104914 ],
       [16.177668 ],
       [45.089394 ],
       [25.394732 ],
       [38.605614 ],
       [43.87104  ],
       [20.404188 ],
       [50.950512 ],
       [52.987156 ],
       [37.875713 ],
       [49.178997 ],
       [49.981792 ],
       [28.489027 ],
       [13.971528 ],
       [26.940176 ],
       [28.72576  ],
       [65.61588  ],
       [18.494287 ],
       [49.34622  ],
       [56.335323 ],
       [46.513573 ],
       [58.800034 ],
       [62.203205 ],
       [26.070837 ],
       [26.587759 ],
       [45.44807  ],
       [66.76432  ],
       [27.229227 ],
       [37.69627  ],
       [41.101303 ],
       [18.014463 ],
       [39.88651  ],
       [24.734938 ],
       [ 2.429742 ],
       [22.553568 ],
       [44.319145 ],
       [49.68003  ],
       [49.938534 ],
       [15.584142 ],
       [19.066893 ],
       [47.981205 ],
       [41.97169  ],
       [52.468235 ],
       [54.062534 ],
       [23.196814 ],
       [50.193737 ],
       [36.311016 ],
       [47.95024  ],
       [20.34569  ],
       [33.24927  ],
       [26.321184 ],
       [17.762262 ],
       [31.731428 ],
       [40.770714 ],
       [25.512663 ],
       [57.82436  ],
       [42.757786 ],
       [25.335081 ],
       [43.922176 ],
       [56.651917 ],
       [55.430233 ],
       [17.785963 ],
       [45.047237 ],
       [26.459356 ],
       [23.895285 ],
       [47.13379  ],
       [32.5926   ],
       [36.503937 ],
       [11.511357 ],
       [42.10555  ],
       [34.32693  ],
       [40.89439  ],
       [49.800632 ],
       [29.939482 ],
       [23.077093 ],
       [32.15749  ],
       [47.95024  ],
       [38.661293 ],
       [33.213486 ],
       [26.258635 ],
       [36.143787 ],
       [50.06441  ],
       [35.963287 ],
       [38.977448 ],
       [ 7.974603 ],
       [28.962023 ],
       [49.538296 ],
       [30.341478 ],
       [11.9818125],
       [28.63452  ],
       [56.11217  ],
       [46.07662  ],
       [61.730503 ],
       [51.460114 ],
       [35.792797 ],
       [46.16151  ],
       [31.96446  ],
       [18.38357  ],
       [83.69451  ],
       [48.820644 ],
       [48.486885 ],
       [28.19708  ],
       [15.541459 ],
       [29.829473 ],
       [47.741123 ],
       [34.68868  ],
       [38.22367  ],
       [17.581656 ],
       [49.854015 ],
       [53.558796 ],
       [37.107407 ],
       [26.537481 ],
       [25.600061 ],
       [46.513573 ],
       [29.724508 ],
       [43.5195   ],
       [23.007677 ],
       [47.981205 ],
       [31.871183 ],
       [56.61127  ],
       [22.631224 ],
       [39.84055  ],
       [34.939808 ],
       [28.494604 ],
       [34.146935 ],
       [40.34594  ],
       [21.697092 ],
       [51.67687  ],
       [24.59347  ],
       [36.0499   ],
       [23.971075 ],
       [46.06286  ],
       [34.53886  ],
       [25.02181  ],
       [23.203535 ],
       [19.287664 ],
       [45.57092  ],
       [35.484146 ],
       [17.543188 ],
       [28.583765 ],
       [23.264048 ],
       [47.95024  ],
       [39.094795 ],
       [32.2964   ],
       [30.492712 ],
       [25.04984  ],
       [23.585516 ],
       [39.87881  ],
       [42.83024  ],
       [21.0437   ],
       [56.46902  ],
       [49.75668  ],
       [24.066904 ],
       [29.175901 ],
       [42.83024  ],
       [22.963259 ],
       [43.72988  ],
       [31.720678 ],
       [53.82723  ],
       [33.65607  ],
       [26.593603 ],
       [17.69752  ],
       [29.19708  ],
       [33.969498 ],
       [36.646538 ],
       [ 3.07982  ],
       [45.45082  ],
       [28.855955 ],
       [40.321728 ],
       [28.473948 ],
       [12.572919 ],
       [39.66692  ],
       [12.227952 ],
       [25.170874 ],
       [49.22666  ],
       [59.45039  ],
       [14.772801 ],
       [27.308374 ],
       [29.163816 ],
       [41.78036  ],
       [35.24233  ],
       [32.42597  ],
       [20.242804 ],
       [28.639345 ],
       [26.95241  ],
       [36.019253 ],
       [43.720837 ],
       [47.65873  ],
       [23.694067 ],
       [19.296057 ],
       [39.05     ],
       [39.13254  ],
       [17.29569  ],
       [42.682587 ],
       [31.272387 ],
       [33.6547   ],
       [44.003162 ],
       [48.727173 ],
       [72.93333  ],
       [41.717445 ],
       [35.66082  ],
       [61.154408 ],
       [70.718575 ],
       [26.507124 ],
       [23.312414 ],
       [20.666998 ],
       [42.37606  ],
       [61.495785 ],
       [57.33208  ],
       [40.755394 ],
       [39.47789  ],
       [57.55586  ],
       [19.270544 ],
       [46.40577  ],
       [37.84559  ],
       [43.77695  ],
       [39.53316  ],
       [24.777906 ],
       [32.626217 ],
       [60.689426 ],
       [45.262836 ],
       [24.838076 ],
       [27.29667  ],
       [10.602204 ]], dtype=float32)

In [19]:
print("Mean absolute error: %.2f" % np.mean(np.absolute(predictions - y_test)))
print("Residual sum of squares (MSE): %.2f" % np.mean((predictions - y_test) ** 2))
from sklearn.metrics import r2_score
print("R2-score: %.2f" % r2_score(y_test, predictions) )

Mean absolute error: 18.21
Residual sum of squares (MSE): 516.03
R2-score: 0.32